
name: FirstHand Choice

description: Get paid to be honest. FirstHand Choice.

baseurl: 

markdown: rdiscount

permalink: pretty

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, .template]
